<<SQL
 SELECT c.LENGTH,s.NAME 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Racine" 
 AND t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

 SELECT SUM(c.LENGTH) 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Racine" AND t.CENTRELINE_ID = c.ID AND s.ID = c.SURVEY_ID AND p.ID = t.PERSON_ID;

 SELECT SUM(c.LENGTH),p.NAME,p.SURNAME FROM PERSON as p,CENTRELINE AS c,EXPLO AS e WHERE e.PERSON_ID=p.ID AND e.CENTRELINE_ID=c.ID
 GROUP BY p.NAME,p.SURNAME
 ORDER BY SUM(c.LENGTH); 

 SELECT SUM(c.LENGTH) FROM CENTRELINE AS c WHERE c.TOPO_DATE >= "2018/01/01" AND c.TOPO_DATE <= "2019/01/01";