sqlite3  <<END_SQL
.open west_plateau.sql
 SELECT c.LENGTH,s.NAME 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Frost" 
 AND t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

 SELECT SUM(c.LENGTH) 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Racine" 
 AND t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

 SELECT SUM(c.LENGTH),p.NAME,p.SURNAME 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Hare" 
 AND t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

  SELECT SUM(c.LENGTH) 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Jurd" 
 AND t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

   SELECT SUM(c.LENGTH) 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE p.SURNAME="Wilson"  AND p.NAME = "James"
 AND t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

  SELECT SUM(c.LENGTH) IN c,p.NAME,p.SURNAME 
 FROM CENTRELINE AS c,TOPO as t,SURVEY AS s,PERSON AS p 
 WHERE t.CENTRELINE_ID = c.ID 
 AND s.ID = c.SURVEY_ID 
 AND p.ID = t.PERSON_ID;

 SELECT SUM(c.LENGTH),p.NAME,p.SURNAME FROM PERSON as p,CENTRELINE AS c,EXPLO AS e WHERE e.PERSON_ID=p.ID AND e.CENTRELINE_ID=c.ID
 GROUP BY p.NAME,p.SURNAME
 ORDER BY SUM(c.LENGTH);