#!/bin/bash

# Get file and survey name
file=$(ls *.th)
name="${file/.th/}"

# Create SVG centerline
echo "source ${file}
layout test
 scale 1 500
 endlayout
export map -projection plan -o ${name}.svg -layout test -layout-debug station-names" >> map.thconfig
therion map.thconfig
rm map.thconfig

# Create blank th2
echo "encoding  utf-8
##XTHERION## xth_me_area_adjust 0 0 1004.000000 1282.000000
##XTHERION## xth_me_area_zoom_to 100

scrap ${name}-1p -projection plan -scale [0.0 0.0 500 1000.0 0.0 0.0 150 300]

endscrap
" >> ${name}-p.th2

# Insert map into th
sed -i "2 a input ${name}-p.th2\n\nmap m${name}-p -projection plan\n    ${name}-1p\nendmap\n" ${file}