#!/usr/bin/env bash

# This script is run before metapost and removes all labels from the data.mp file
# that have a level greater than the max level defined in the config.

MAX_LEVEL=$(cat data.mp | grep 'set_label_level(' | cut -c 18)
echo "Beginning metapost label level shim - max level is $MAX_LEVEL"

mv data.mp data.mp.tmp

REMOVED=0
LEVEL=0
while IFS= read -r line; do
    if [[ "$line" == *"ATTR_lvl :="* ]]; then
        LEVEL=$(echo $line | cut -c 14)
    fi
    if [[ "$line" == *"p_label"* ]]; then
        if [ "$LEVEL" -gt "$MAX_LEVEL" ]; then
            echo "p_label(btex etex,(0,0),0.0,p_label_mode_label);" >>data.mp
            REMOVED=$(($REMOVED + 1))
        else
            echo "$line" >>data.mp
        fi
        LEVEL=0
    else
        echo "$line" >>data.mp
    fi
done <data.mp.tmp

echo "Label level shim complete - removed $REMOVED labels"

mpost $@
